name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Prettier Check
              shell: bash
              run: yarn && yarn prettier:check

           # - name: Lint Check
           #   shell: bash
           #   run: yarn && yarn lint

           # - name: Unit test
           #   shell: bash
           #   run: yarn && yarn test:ci

            - name: Build
              shell: bash
              run: yarn && yarn build
